Controllers/CategoryController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new CategoryPhoto
            {
                category = new Category()
            };
            return View(model);
        }


        [HttpPost]
        public IActionResult GetPhotos(string category, string categories)
        {
            var selectedCategory = category;
            var allCategories = categories;
            var a = 1;

            var photos = _context.Photos
                .Where(p => p.Category == selectedCategory)
                .ToList();

            var model = new CategoryPhoto
            {
                category = new Category(),
                photos = photos
            };
            return View("Index", model);

        }

    }
}

Controllers/ProfileController.cs
using System.Security.Cryptography;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProfileController:Controller
    {
        /**public IActionResult Index()
        {
            return View();
        }**/
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;


        public ProfileController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Photos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Photos.ToListAsync());
        }

        // GET: Photos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Photos == null)
            {
                return NotFound();
            }

            var photos = await _context.Photos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (photos == null)
            {
                return NotFound();
            }

            return View(photos);
        }

        // GET: Photos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Photos/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<ImageMetadata> metadata, IEnumerable<IFormFile> imageFiles)
        {
            // Iterate through the list of image files
            for (int i = 0; i < imageFiles.Count(); i++)
            {
                var image = imageFiles.ElementAt(i);
                if (image.Length > 0)
                {
                    // Create a new Photos object for each file
                    var photos = new Photos
                    {
                        Category = metadata[i].Category,
                        Description = metadata[i].Description
                    };

                    // Save image to wwwroot/image
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = image.FileName;
                    photos.ImagePath = "~/Image/" + fileName;
                    string path = Path.Combine(wwwRootPath + "/Image/", image.FileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await image.CopyToAsync(fileStream);
                    }

                    // Generate thumbnail and save to wwwroot/image/thumbnail
                    string thumbnailPath = Path.Combine(wwwRootPath + "/Image/Thumbnail/", image.FileName);
                    using (var imageStream = new FileStream(path, FileMode.Open))
                    using (var thumbnailStream = new FileStream(thumbnailPath, FileMode.Create))
                    {
                        var imageObject = SixLabors.ImageSharp.Image.Load(imageStream);
                        imageObject.Mutate(x => x.Resize(new ResizeOptions
                        {
                            Size = new SixLabors.ImageSharp.Size(0, 200),
                            Mode = ResizeMode.Max
                        }));
                        imageObject.SaveAsJpeg(thumbnailStream);
                    }

                    // Insert record
                    _context.Add(photos);
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index", "Home");
        }



        // GET: Photos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Photos == null)
            {
                return NotFound();
            }

            var photos = await _context.Photos.FindAsync(id);
            if (photos == null)
            {
                return NotFound();
            }
            return View(photos);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Category,ImagePath,Description,DateAdded")] Photos photos)
        {
            if (id != photos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(photos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhotosExists(photos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(photos);
        }

        // GET: Photos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Photos == null)
            {
                return NotFound();
            }

            var photos = await _context.Photos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (photos == null)
            {
                return NotFound();
            }

            return View(photos);
        }

        private bool PhotosExists(int id)
        {
            return _context.Photos.Any(e => e.Id == id);
        }
    }
}

Controllers/RegisterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Controllers;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
  
    public class RegisterController : Controller
    {
        private readonly ApplicationDbContext _db;

        public RegisterController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult SuccesfullySignUp()
        {

           
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(User obj)
        {
            
            
            if (ModelState.IsValid)
            {
                _db.Users.Add(obj);
                
                _db.SaveChanges();
                return RedirectToAction("SuccesfullySignUp");
            }

            return View(obj);
            
        }


    }
}


    

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor Accessor;



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Application</title>
   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhotoSharing</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                       
                        
                       
                        
                         @if (@Accessor.HttpContext.Session.GetString("UserName") == null)
                            {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Login2" asp-action="Login2">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Register" asp-action="Create">Register</a>
                        </li>
                            }

                        <li class="nav-item">
                           @if (@Accessor.HttpContext.Session.GetString("UserName") != null)
                            {
                            
                               
                            
                            
                                <a class="nav-link" asp-area="" asp-controller="Login2" asp-action="Logout">Logout</a>
                            
                          
                            }
                       </li>
                        <li class="nav-item">
                            @if (@Accessor.HttpContext.Session.GetString("UserName") != null)
                            {

                                <a class="nav-link" asp-area="" asp-controller="Profile" asp-action="Create">Profile</a>

                            }
                        </li>

                         <li class="nav-item">
                             <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Category</a>

                            
                        </li>
                        
                    </ul>
                    
                        @using (Html.BeginForm("Search", "Home"))
                    {
                        
                        
                           <li class="nav-item">
                            <input class="form-control me-sm-2" type="search" placeholder="Search" name="searchString">
                             </li>
                              <li class="nav-item">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                            </li>
                        }

                    
                </div>
                </div>
        </nav>
   
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>